version: "3"
services:
    db:
        image: "mongo"
        environment:
            MONGO_INITDB_ROOT_USERNAME: "root"
            MONGO_INITDB_ROOT_PASSWORD: "root"
            MONGO_INITDB_DATABASE: "molotov"
        ports:
            - 27017:27017
